image: openjdk:8-jdk

variables:
  ANDROID_TARGET_SDK: "26"
  ANDROID_BUILD_TOOLS: "26.0.1"
  ANDROID_SDK_TOOLS: "26.0.2"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip -q android-sdk.zip -d android-sdk-linux
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x code/gradlew

stages:
  - build
  - test

build:
  stage: build
  script:
    - code/gradlew init
  artifacts:
    paths:
    - code/app/build/outputs/

unitTests:
  stage: test
  script:
    - code/gradlew test

